#!/usr/bin/python3

import urllib.parse
import os
import sys
import json
import subprocess

if len(sys.argv) <= 1:
    print(f'Usage: {sys.argv[0]} program [args...]')
    sys.exit(1)

if sys.argv[1] != 'cargo':
    program = sys.argv[1]
    if program[0] != '/':
        program = os.path.join(os.getcwd(), program)
    config = {
        'program': program,
        'args': sys.argv[2:],
#        'stopOnEntry': True,
    }
else:
    config = {
        'cargo': {
            'args': [sys.argv[2]] + ['--manifest-path=${workspaceFolder}/Cargo.toml'] + sys.argv[3:]
        },
#       'stopOnEntry': True,
    }

print(config)

url = 'vscode://vadimcn.vscode-lldb/launch/config'
url += '?' + urllib.parse.quote(json.dumps(config))

subprocess.run([
    'code',
    '--open-url',
    url,
])
