/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "grpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helloworld_HelloRequest, helloworld_HelloRequest, AUTO)


PB_BIND(helloworld_HelloReply, helloworld_HelloReply, AUTO)



/* Server stub */
rpc_status helloworld_Greeter::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory){
    switch(methodId){
        case SayHello_id:
            return SayHello_stub(codec, messageFactory, sequence);
        default:
            return rpc_status::kErpcStatus_UnknownName;
    }
}

rpc_status helloworld_Greeter::SayHello_stub(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence) {
    //serilaize request message
    helloworld_HelloRequest request = helloworld_HelloRequest_init_default;
    pb_istream_t istream = pb_istream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
    if(!pb_decode(&istream, helloworld_HelloRequest_fields, &request)){
        return Fail;
    }

    //call method
    helloworld_HelloReply response = helloworld_HelloReply_init_default;
    SayHello(&request, &response);

    // preparing codec for serializing data
    codec->reset();
    codec->startWriteMessage(kReplyMessage, m_serviceId, SayHello_id, sequence);
    pb_ostream_t ostream = pb_ostream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
    if(!pb_encode(&ostream, helloworld_HelloReply_fields, &response)){
        return Fail;
}
    return codec->getStatus() ? Success : Fail;
}

/* Client stub */
void helloworld_Greeter_Client::SayHello(helloworld_HelloRequest *req, helloworld_HelloReply *rsp) {
    rpc_status err = rpc_status::Success;

    // Get a new request.
    RequestContext request = createRequest(false);
    // Encode the request.
    Codec * codec = request.getCodec();
    if (codec == NULL){
        err = rpc_status::MemoryError;
    }
    else{
        codec->startWriteMessage(kInvocationMessage, helloworld_Greeter_id, _helloworld_Greeter::SayHello_id, request.getSequence());
        // Serialize the request.
        pb_ostream_t ostream = pb_ostream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
        if(!pb_encode(&ostream, helloworld_HelloRequest_fields, &req)){
        }
        // Send message to server
        performRequest(request);
        // Wait for response.
        sleep(1);
        pb_istream_t istream = pb_istream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
        if(!pb_decode(&istream, helloworld_HelloReply_fields, &rsp)){
        }
    }

    // Dispose of the request.
    releaseRequest(request);
    return;
}
