/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "idl.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(myrpc_proto, myrpc_proto, AUTO)


PB_BIND(myrpc_proto_Nested, myrpc_proto_Nested, AUTO)


PB_BIND(myrpc_InputTest, myrpc_InputTest, AUTO)


PB_BIND(myrpc_OutputTest, myrpc_OutputTest, AUTO)



/* Server stub */
rpc_status myrpc_MatrixMultiplyService::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory){
    switch(methodId){
        case myrpctest_id:
            return myrpctest_stub(codec, messageFactory, sequence);
        default:
            return rpc_status::kErpcStatus_UnknownName;
    }
}

rpc_status myrpc_MatrixMultiplyService::myrpctest_stub(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence) {
    //serilaize request message
    myrpc_InputTest request = myrpc_InputTest_init_default;
    pb_istream_t istream = pb_istream_from_buffer(codec->getBuffer()->get()+codec->getBuffer()->getUsed(), codec->getBuffer()->getLeft());
    if (!pb_decode(&istream, myrpc_InputTest_fields, &request)) {
        printf("%s", istream.errmsg);
        return Fail;
    }

    //call method
    myrpc_OutputTest response = myrpc_OutputTest_init_default;
    this->myrpctest(&request, &response);

    // preparing codec for serializing data
    codec->reset();
    codec->startWriteMessage(kReplyMessage, m_serviceId, myrpctest_id, sequence);
    pb_ostream_t ostream = pb_ostream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
    if(!pb_encode(&ostream, myrpc_OutputTest_fields, &response)){
        return Fail;
    }
    return codec->isStatusOk() ? Success : Fail;
}

/* Client stub */
void myrpc_MatrixMultiplyService_Client::myrpctest(myrpc_InputTest *req, myrpc_OutputTest *rsp) {
    rpc_status err = rpc_status::Success;

    // Get a new request.
    RequestContext request = createRequest(false);
    // Encode the request.
    Codec * codec = request.getCodec();
    if (codec == NULL){
        err = rpc_status::MemoryError;
    }
    else{
        codec->startWriteMessage(kInvocationMessage, myrpc_MatrixMultiplyService_id, myrpc_MatrixMultiplyService::_myrpc_MatrixMultiplyService_method_id::myrpctest_id, request.getSequence());
        m_transport->send(request.getCodec()->getBuffer());
        // Serialize the request.
        pb_ostream_t ostream = pb_ostream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
        if(!pb_encode(&ostream, myrpc_InputTest_fields, &req)){
        }
        request.getCodec()->getBuffer()->setUsed(ostream.bytes_written);
        // Send message to server
        performRequest(request);
        // Wait for response.
        pb_istream_t istream = pb_istream_from_buffer(codec->getBuffer()->get(), codec->getBuffer()->getLength());
        if(!pb_decode(&istream, myrpc_OutputTest_fields, &rsp)){
        }
    }

    // Dispose of the request.
    releaseRequest(request);
    return;
}
