/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.9.1 on Tue Mar 28 10:14:18 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_qaq_h_)
#define _qaq_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"
#include "rpc_client.h"

#if 10901 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief aaa identifiers */
enum _aaa_ids
{
    kaaa_service_id = 1,
    kaaa_erpctest_id = 1,
};


/*!
 * @brief Service subclass for aaa.
 */
class aaaClient : public erpc::Client
{
public:
    aaaClient(const char *host, uint16_t port, erpc::MessageBufferFactory *messageFactory) : erpc::Client(host, port, messageFactory) {}
    ~aaaClient(){}
    /*! @brief Client shim for erpctest of aaa interface. */
    void erpctest(const char * str);
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name aaa
//@{
void erpctest(const char * str);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _qaq_h_
