@startuml stub
class MatrixMultiplyService_service extends Service{
    --switcher--
    +virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec *codec, erpc::MessageBufferFactory *messageFactory);
    --shim of method--
    #erpc_status_t erpcMatrixMultiply_shim(erpc::Codec *codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
    #erpc_status_t erpctest_shim(erpc::Codec *codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
}

@enduml