#ifndef PORT_CONST_H_
#define PORT_CONST_H_

#ifndef ERPC_DEFAULT_BUFFER_SIZE
#define ERPC_DEFAULT_BUFFER_SIZE (256U)
#endif

#ifndef CONFIG_MAX_PTHREAD_NAME_LEN
#define CONFIG_MAX_PTHREAD_NAME_LEN (16U)
#endif

#endif  // PORT_CONST_H_